### ISSUE TITLE
Adding FAQ

### ISSUE THREAD

**Issue by siri-chandana-macha** [kvcops/KV-Nexus#21] opened 2024-10-26 00:32 UTC
An FAQ section is essential for enhancing user experience by providing quick answers to common questions, allowing users to navigate and utilize the app's features with ease. It helps clarify functionality, such as how to interact with the AI chatbots ,reducing user confusion and support requests.

@kvcops please assign this issue under gssoc-ext , hacktoberfest-accepted and level2.

**Comment by kvcops** [comment] 2024-10-26 01:13
yep...try adding this feature .

**Comment by InderParmar** [comment] 2024-10-26 04:25
Hi, can you please assign this issue to me, I am eager to work on this?

**Comment by kvcops** [comment] 2024-10-26 04:48
Ok ...

**Comment by techy4shri** [comment] 2024-10-26 10:50
@kvcops only one person per issue is assigned unless the issue is complex in nature. Removing the second assigneee.
@InderParmar do not comment to be assigned on an already assigned issue.

**Comment by kvcops** [comment] 2024-10-26 11:16
Ok...I will try not to add multiple people for a single issue

**Closed** 2024-10-27 07:57 UTC
Labels: enhancement, gssoc-ext, level1, Hacktoberfest, Hacktoberfest-accepted
